name: Publish Release

on:
  push:
    branches:
     - main
     - 'release/**'

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build Binary
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/branded-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: branded-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/branded-${{ matrix.goos }}-${{ matrix.goarch }}
